/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CamisetaController;
import dao.ExceptionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaCadastroCamisetas extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAcessorio
     */
    private TelaPrincipal telaPrincipal;
    
    public TelaCadastroCamisetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroCamisetas = new javax.swing.JLabel();
        jPanelCadastroAcessório = new javax.swing.JPanel();
        jLabelCamisetaTime = new javax.swing.JLabel();
        jTextFieldCamisetaTime = new javax.swing.JTextField();
        jLabelAcessorioBolaPreco = new javax.swing.JLabel();
        jTextFieldCamisetaModelo = new javax.swing.JTextField();
        CadastroCamisetaSalvar = new javax.swing.JButton();
        CadastroCamisetaLimpar = new javax.swing.JButton();
        jButtonCadastroCamisetasVoltar = new javax.swing.JButton();
        jLabelCamisetaModelo = new javax.swing.JLabel();
        jTextFieldValorCamiseta = new javax.swing.JTextField();
        jLabelCamisetaTamanho = new javax.swing.JLabel();
        jTextFieldCamisetaTamanho = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toca a Boca -> Cadastro de Camisetas");
        setResizable(false);

        jLabelCadastroCamisetas.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jLabelCadastroCamisetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo.png"))); // NOI18N
        jLabelCadastroCamisetas.setText("Cadastro de Camisetas");
        jLabelCadastroCamisetas.setToolTipText("");

        jPanelCadastroAcessório.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroAcessório.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelCamisetaTime.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelCamisetaTime.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCamisetaTime.setText("Time:");

        jTextFieldCamisetaTime.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldCamisetaTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCamisetaTime.setToolTipText("Infome o time da camiseta");
        jTextFieldCamisetaTime.setActionCommand("<Não Definido>");
        jTextFieldCamisetaTime.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldCamisetaTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCamisetaTimeActionPerformed(evt);
            }
        });

        jLabelAcessorioBolaPreco.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelAcessorioBolaPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAcessorioBolaPreco.setText("Preço: ");

        jTextFieldCamisetaModelo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldCamisetaModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCamisetaModelo.setToolTipText("Infome o modelo da camiseta");
        jTextFieldCamisetaModelo.setActionCommand("<Não Definido>");
        jTextFieldCamisetaModelo.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldCamisetaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCamisetaModeloActionPerformed(evt);
            }
        });

        CadastroCamisetaSalvar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        CadastroCamisetaSalvar.setText("Enviar");
        CadastroCamisetaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCamisetaSalvar(evt);
            }
        });

        CadastroCamisetaLimpar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        CadastroCamisetaLimpar.setText("Limpar");
        CadastroCamisetaLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCamisetaLimparActionPerformed(evt);
            }
        });

        jButtonCadastroCamisetasVoltar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jButtonCadastroCamisetasVoltar.setText("Voltar");
        jButtonCadastroCamisetasVoltar.setActionCommand("Voltar");
        jButtonCadastroCamisetasVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCamisetasVoltarActionPerformed(evt);
            }
        });

        jLabelCamisetaModelo.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelCamisetaModelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCamisetaModelo.setText("Modelo:");

        jTextFieldValorCamiseta.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldValorCamiseta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldValorCamiseta.setToolTipText("Infome o preço do produto");
        jTextFieldValorCamiseta.setActionCommand("<Não Definido>");
        jTextFieldValorCamiseta.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldValorCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCamisetaActionPerformed(evt);
            }
        });

        jLabelCamisetaTamanho.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelCamisetaTamanho.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCamisetaTamanho.setText("Tamanho:");

        jTextFieldCamisetaTamanho.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldCamisetaTamanho.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCamisetaTamanho.setToolTipText("Infome o tamanho da camiseta");
        jTextFieldCamisetaTamanho.setActionCommand("<Não Definido>");
        jTextFieldCamisetaTamanho.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldCamisetaTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCamisetaTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroAcessórioLayout = new javax.swing.GroupLayout(jPanelCadastroAcessório);
        jPanelCadastroAcessório.setLayout(jPanelCadastroAcessórioLayout);
        jPanelCadastroAcessórioLayout.setHorizontalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCamisetaModelo)
                    .addComponent(jLabelCamisetaTime)
                    .addComponent(jLabelCamisetaTamanho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCamisetaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCamisetaTime, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jTextFieldCamisetaModelo))
                .addGap(0, 77, Short.MAX_VALUE))
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabelAcessorioBolaPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastroCamisetaSalvar))
                .addGap(68, 68, 68)
                .addComponent(CadastroCamisetaLimpar)
                .addGap(68, 68, 68)
                .addComponent(jButtonCadastroCamisetasVoltar)
                .addGap(24, 24, 24))
        );
        jPanelCadastroAcessórioLayout.setVerticalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCamisetaTime, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCamisetaTime))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamisetaModelo)
                    .addComponent(jTextFieldCamisetaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamisetaTamanho)
                    .addComponent(jTextFieldCamisetaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAcessorioBolaPreco)
                    .addComponent(jTextFieldValorCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroCamisetaLimpar)
                    .addComponent(CadastroCamisetaSalvar)
                    .addComponent(jButtonCadastroCamisetasVoltar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabelCadastroCamisetas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroCamisetas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCamisetaTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCamisetaTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCamisetaTimeActionPerformed

    private void jTextFieldCamisetaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCamisetaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCamisetaModeloActionPerformed

    private void CadastroCamisetaSalvar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCamisetaSalvar
        String time = jTextFieldCamisetaTime.getText();
        String modelo = jTextFieldCamisetaModelo.getText();
        String tamanho = jTextFieldCamisetaTamanho.getText();
        Double valor = Double.parseDouble(jTextFieldValorCamiseta.getText());
       
        boolean sucesso;
        
        try {
            CamisetaController camisetaController = new CamisetaController();
            sucesso = camisetaController.cadastrarCamiseta(jTextFieldCamisetaTime.getText(), jTextFieldCamisetaModelo.getText(), jTextFieldCamisetaTamanho.getText(), valor);
            
                if(sucesso == true && tamanho.length() > 0 && tamanho.length() < 3){
                    JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
                    this.CadastroCamisetaLimparActionPerformed(evt);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente!");
                }
        } catch (HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Erro:" + ex);
        } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCadastroCamisetas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastroCamisetaSalvar

    private void CadastroCamisetaLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCamisetaLimparActionPerformed
        jTextFieldCamisetaTime.setText("");
        jTextFieldCamisetaModelo.setText("");
        jTextFieldCamisetaTamanho.setText("");
        jTextFieldValorCamiseta.setText("");
    }//GEN-LAST:event_CadastroCamisetaLimparActionPerformed

    private void jButtonCadastroCamisetasVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCamisetasVoltarActionPerformed
      /*  jTextFieldDescricaoAcessorio.setText("");
        jTextFieldValorAcessorio1.setText(""); */
        
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroCamisetasVoltarActionPerformed

    private void jTextFieldValorCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCamisetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorCamisetaActionPerformed

    private void jTextFieldCamisetaTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCamisetaTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCamisetaTamanhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCamisetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCamisetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCamisetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCamisetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCamisetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroCamisetaLimpar;
    private javax.swing.JButton CadastroCamisetaSalvar;
    private javax.swing.JButton jButtonCadastroCamisetasVoltar;
    private javax.swing.JLabel jLabelAcessorioBolaPreco;
    private javax.swing.JLabel jLabelCadastroCamisetas;
    private javax.swing.JLabel jLabelCamisetaModelo;
    private javax.swing.JLabel jLabelCamisetaTamanho;
    private javax.swing.JLabel jLabelCamisetaTime;
    private javax.swing.JPanel jPanelCadastroAcessório;
    private javax.swing.JTextField jTextFieldCamisetaModelo;
    private javax.swing.JTextField jTextFieldCamisetaTamanho;
    private javax.swing.JTextField jTextFieldCamisetaTime;
    private javax.swing.JTextField jTextFieldValorCamiseta;
    // End of variables declaration//GEN-END:variables
}
