/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BolaController;
import dao.ExceptionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaCadastroBola extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAcessorio
     */
    private TelaPrincipal telaPrincipal;
    
    public TelaCadastroBola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroBola = new javax.swing.JLabel();
        jPanelCadastroAcessório = new javax.swing.JPanel();
        jLabelBolaModelo = new javax.swing.JLabel();
        jTextFieldBolaModelo = new javax.swing.JTextField();
        jLabelAcessorioBolaPreco = new javax.swing.JLabel();
        jTextFieldMarcaBola = new javax.swing.JTextField();
        jButtonCadastroBolaEnviar = new javax.swing.JButton();
        CadastroAcessorioLimpar = new javax.swing.JButton();
        jButtonCadastroBolaVoltar = new javax.swing.JButton();
        jLabelBolaMarca = new javax.swing.JLabel();
        jTextFieldBolaValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toca a Boca -> Cadastro de Bolas");
        setResizable(false);

        jLabelCadastroBola.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jLabelCadastroBola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo.png"))); // NOI18N
        jLabelCadastroBola.setText("Cadastro de Bolas");
        jLabelCadastroBola.setToolTipText("");

        jPanelCadastroAcessório.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroAcessório.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelBolaModelo.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelBolaModelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBolaModelo.setText("Modelo:");

        jTextFieldBolaModelo.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldBolaModelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBolaModelo.setToolTipText("Infome o modelo da bola");
        jTextFieldBolaModelo.setActionCommand("<Não Definido>");
        jTextFieldBolaModelo.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldBolaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBolaModeloActionPerformed(evt);
            }
        });

        jLabelAcessorioBolaPreco.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelAcessorioBolaPreco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAcessorioBolaPreco.setText("Preço: ");

        jTextFieldMarcaBola.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldMarcaBola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMarcaBola.setToolTipText("Infome a marca da bola");
        jTextFieldMarcaBola.setActionCommand("<Não Definido>");
        jTextFieldMarcaBola.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldMarcaBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaBolaActionPerformed(evt);
            }
        });

        jButtonCadastroBolaEnviar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jButtonCadastroBolaEnviar.setText("Enviar");
        jButtonCadastroBolaEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBolaEnviar(evt);
            }
        });

        CadastroAcessorioLimpar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        CadastroAcessorioLimpar.setText("Limpar");
        CadastroAcessorioLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAcessorioLimparActionPerformed(evt);
            }
        });

        jButtonCadastroBolaVoltar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jButtonCadastroBolaVoltar.setText("Voltar");
        jButtonCadastroBolaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroBolaVoltarActionPerformed(evt);
            }
        });

        jLabelBolaMarca.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelBolaMarca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBolaMarca.setText("Marca:");

        jTextFieldBolaValor.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldBolaValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBolaValor.setToolTipText("Infome o preço do produto");
        jTextFieldBolaValor.setActionCommand("<Não Definido>");
        jTextFieldBolaValor.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldBolaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBolaValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroAcessórioLayout = new javax.swing.GroupLayout(jPanelCadastroAcessório);
        jPanelCadastroAcessório.setLayout(jPanelCadastroAcessórioLayout);
        jPanelCadastroAcessórioLayout.setHorizontalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastroBolaEnviar)
                            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                                .addComponent(jLabelAcessorioBolaPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBolaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addComponent(CadastroAcessorioLimpar)
                        .addGap(68, 68, 68)
                        .addComponent(jButtonCadastroBolaVoltar))
                    .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBolaMarca)
                            .addComponent(jLabelBolaModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMarcaBola, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBolaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelCadastroAcessórioLayout.setVerticalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBolaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBolaModelo))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBolaMarca)
                    .addComponent(jTextFieldMarcaBola, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAcessorioBolaPreco)
                    .addComponent(jTextFieldBolaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroAcessorioLimpar)
                    .addComponent(jButtonCadastroBolaEnviar)
                    .addComponent(jButtonCadastroBolaVoltar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabelCadastroBola)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCadastroBola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMarcaBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaBolaActionPerformed

    private void CadastroBolaEnviar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBolaEnviar
        String modelo = jTextFieldBolaModelo.getText();
        String Marca = jTextFieldMarcaBola.getText();
        Double valor = Double.parseDouble(jTextFieldBolaValor.getText());
        boolean sucesso;
      
        try{
            BolaController bolaController = new BolaController();
            sucesso = bolaController.cadastrarBola(jTextFieldBolaModelo.getText(),jTextFieldMarcaBola.getText(), valor);
            
            if(sucesso = true){
                    JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
                    this.CadastroAcessorioLimparActionPerformed(evt);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente!");
                }
        } catch (HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Erro:" + ex); 
        } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCadastroBola.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastroBolaEnviar

    private void CadastroAcessorioLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAcessorioLimparActionPerformed
        jTextFieldBolaModelo.setText("");
        jTextFieldMarcaBola.setText("");
        jTextFieldBolaValor.setText("");
    }//GEN-LAST:event_CadastroAcessorioLimparActionPerformed

    private void jButtonCadastroBolaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroBolaVoltarActionPerformed
      /*jTextFieldDescricaoAcessorio.setText("");
        jTextFieldValorAcessorio1.setText(""); */
        
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonCadastroBolaVoltarActionPerformed

    private void jTextFieldBolaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBolaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBolaValorActionPerformed

    private void jTextFieldBolaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBolaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBolaModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroAcessorioLimpar;
    private javax.swing.JButton jButtonCadastroBolaEnviar;
    private javax.swing.JButton jButtonCadastroBolaVoltar;
    private javax.swing.JLabel jLabelAcessorioBolaPreco;
    private javax.swing.JLabel jLabelBolaMarca;
    private javax.swing.JLabel jLabelBolaModelo;
    private javax.swing.JLabel jLabelCadastroBola;
    private javax.swing.JPanel jPanelCadastroAcessório;
    private javax.swing.JTextField jTextFieldBolaModelo;
    private javax.swing.JTextField jTextFieldBolaValor;
    private javax.swing.JTextField jTextFieldMarcaBola;
    // End of variables declaration//GEN-END:variables
}
