/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ClienteController;
import dao.ExceptionDAO;
import java.awt.HeadlessException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAcessorio
     */
    private TelaPrincipal telaPrincipal;
    
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadastroCliente = new javax.swing.JLabel();
        jPanelCadastroAcessório = new javax.swing.JPanel();
        jLabelClienteNome = new javax.swing.JLabel();
        jTextFieldClienteNome = new javax.swing.JTextField();
        jLabelClienteNewsletter = new javax.swing.JLabel();
        jTextFieldClienteEmail = new javax.swing.JTextField();
        CadastroClienteEnviar = new javax.swing.JButton();
        CadastroClienteLimpar = new javax.swing.JButton();
        jButtonCadastroClienteVoltar = new javax.swing.JButton();
        jLabelClienteEmail = new javax.swing.JLabel();
        jLabelClienteTelefone = new javax.swing.JLabel();
        jTextFieldClienteCpf = new javax.swing.JTextField();
        jLabelClienteCpf = new javax.swing.JLabel();
        jTextFieldClienteTelefone = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Toca a Boca -> Cadastro de Clientes");
        setResizable(false);

        jLabelCadastroCliente.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jLabelCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo.png"))); // NOI18N
        jLabelCadastroCliente.setText("Cadastro de Cliente");
        jLabelCadastroCliente.setToolTipText("");

        jPanelCadastroAcessório.setBackground(new java.awt.Color(102, 102, 102));
        jPanelCadastroAcessório.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelClienteNome.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelClienteNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClienteNome.setText("Nome:");

        jTextFieldClienteNome.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldClienteNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldClienteNome.setToolTipText("Infome o nome do cliente");
        jTextFieldClienteNome.setActionCommand("<Não Definido>");
        jTextFieldClienteNome.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldClienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteNomeActionPerformed(evt);
            }
        });

        jLabelClienteNewsletter.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelClienteNewsletter.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClienteNewsletter.setText("Cliente deseja assinar a newsletter?");

        jTextFieldClienteEmail.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jTextFieldClienteEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldClienteEmail.setToolTipText("Infome o email do cliente");
        jTextFieldClienteEmail.setActionCommand("<Não Definido>");
        jTextFieldClienteEmail.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldClienteEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteEmailActionPerformed(evt);
            }
        });

        CadastroClienteEnviar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        CadastroClienteEnviar.setText("Enviar");
        CadastroClienteEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteEnviar(evt);
            }
        });

        CadastroClienteLimpar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        CadastroClienteLimpar.setText("Limpar");
        CadastroClienteLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteLimpar(evt);
            }
        });

        jButtonCadastroClienteVoltar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        jButtonCadastroClienteVoltar.setText("Voltar");
        jButtonCadastroClienteVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClienteVoltarActionPerformed(evt);
            }
        });

        jLabelClienteEmail.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelClienteEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClienteEmail.setText("Email:");

        jLabelClienteTelefone.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelClienteTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClienteTelefone.setText("Telefone:");

        jTextFieldClienteCpf.setFont(new java.awt.Font("Work Sans Medium", 0, 24)); // NOI18N
        jTextFieldClienteCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldClienteCpf.setToolTipText("Infome o cpf do cliente");
        jTextFieldClienteCpf.setActionCommand("<Não Definido>");
        jTextFieldClienteCpf.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldClienteCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteCpfActionPerformed(evt);
            }
        });

        jLabelClienteCpf.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jLabelClienteCpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClienteCpf.setText("CPF:");

        jTextFieldClienteTelefone.setFont(new java.awt.Font("Work Sans Medium", 0, 24)); // NOI18N
        jTextFieldClienteTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldClienteTelefone.setToolTipText("Infome o telefone do cliente");
        jTextFieldClienteTelefone.setActionCommand("<Não Definido>");
        jTextFieldClienteTelefone.setBorder(new javax.swing.border.MatteBorder(null));
        jTextFieldClienteTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteTelefoneActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Nao" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroAcessórioLayout = new javax.swing.GroupLayout(jPanelCadastroAcessório);
        jPanelCadastroAcessório.setLayout(jPanelCadastroAcessórioLayout);
        jPanelCadastroAcessórioLayout.setHorizontalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(CadastroClienteEnviar)
                .addGap(68, 68, 68)
                .addComponent(CadastroClienteLimpar)
                .addGap(67, 67, 67)
                .addComponent(jButtonCadastroClienteVoltar)
                .addGap(24, 211, Short.MAX_VALUE))
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                        .addComponent(jLabelClienteNewsletter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelClienteEmail)
                            .addComponent(jLabelClienteNome)
                            .addComponent(jLabelClienteTelefone)
                            .addComponent(jLabelClienteCpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldClienteNome, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                            .addComponent(jTextFieldClienteEmail)
                            .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldClienteTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jTextFieldClienteCpf, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCadastroAcessórioLayout.setVerticalGroup(
            jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroAcessórioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteNome))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteEmail)
                    .addComponent(jTextFieldClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteCpf))
                .addGap(22, 22, 22)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldClienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClienteTelefone))
                .addGap(24, 24, 24)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteNewsletter)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelCadastroAcessórioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroClienteEnviar)
                    .addComponent(CadastroClienteLimpar)
                    .addComponent(jButtonCadastroClienteVoltar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabelCadastroCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCadastroAcessório, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldClienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteNomeActionPerformed

    private void jTextFieldClienteEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteEmailActionPerformed

    private void CadastroClienteEnviar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteEnviar
        String nome = jTextFieldClienteNome.getText();
        String email = jTextFieldClienteEmail.getText();
        String cpf = jTextFieldClienteCpf.getText();
        String telefone = jTextFieldClienteTelefone.getText();
        String newsletter = jComboBox1.getSelectedItem().toString();
       
        boolean sucesso;
        
        try {
            ClienteController clienteController = new ClienteController();
            sucesso = clienteController.cadastrarCliente(jTextFieldClienteNome.getText(), jTextFieldClienteEmail.getText(), jTextFieldClienteCpf.getText(), jTextFieldClienteTelefone.getText(), newsletter);
            if(cpf.length() > 0 && cpf.length() < 12 && telefone.length() > 0 && telefone.length() < 12) {
                if(sucesso == true){
                    JOptionPane.showMessageDialog(null, "O cadastro foi realizado com sucesso!");
                    this.CadastroClienteLimpar(evt);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente!");
                }
            }
            else {
                 JOptionPane.showMessageDialog(null, "Os campos cpf ou telefone não foram preenchidos corretamente!");
            }
        } catch (HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Erro:" + ex);
        } catch (ExceptionDAO ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastroClienteEnviar

    private void CadastroClienteLimpar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteLimpar
        jTextFieldClienteNome.setText("");
        jTextFieldClienteEmail.setText("");   
        jTextFieldClienteCpf.setText("");
        jTextFieldClienteTelefone.setText("");        
    }//GEN-LAST:event_CadastroClienteLimpar

    private void jButtonCadastroClienteVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClienteVoltarActionPerformed
        /*  jTextFieldDescricaoAcessorio.setText("");
        jTextFieldValorAcessorio1.setText(""); */
        
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        
        this.dispose();              
    }//GEN-LAST:event_jButtonCadastroClienteVoltarActionPerformed

    private void jTextFieldClienteCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteCpfActionPerformed

    private void jTextFieldClienteTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteTelefoneActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroClienteEnviar;
    private javax.swing.JButton CadastroClienteLimpar;
    private javax.swing.JButton jButtonCadastroClienteVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelCadastroCliente;
    private javax.swing.JLabel jLabelClienteCpf;
    private javax.swing.JLabel jLabelClienteEmail;
    private javax.swing.JLabel jLabelClienteNewsletter;
    private javax.swing.JLabel jLabelClienteNome;
    private javax.swing.JLabel jLabelClienteTelefone;
    private javax.swing.JPanel jPanelCadastroAcessório;
    private javax.swing.JTextField jTextFieldClienteCpf;
    private javax.swing.JTextField jTextFieldClienteEmail;
    private javax.swing.JTextField jTextFieldClienteNome;
    private javax.swing.JTextField jTextFieldClienteTelefone;
    // End of variables declaration//GEN-END:variables
}
