/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
/**
 *
 * @author gabri
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private TelaCadastroAcessorio telaCadastroAcessorio;
    private TelaCadastroBola telaCadastroBola;
    private TelaCadastroCamisetas telaCadastroCamisetas;
    private TelaCadastroChuteiras telaCadastroChuteiras;
    private TelaCadastroCliente telaCadastroCliente;
    private TelaConsultaEstoque telaConsultaEstoque;
    private TelaRealizarVenda telaRealizarVenda;
    private TelaConsultaVendas telaConsultarVendas;
    
    
    public TelaPrincipal() {
        initComponents();
    }
    
    public TelaPrincipal(TelaCadastroAcessorio telaCadastroAcessorio) {
        this.telaCadastroAcessorio = telaCadastroAcessorio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFundo = new javax.swing.JLabel();
        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuRealizarVenda = new javax.swing.JMenu();
        jMenuHistoricoVenda = new javax.swing.JMenu();
        jMenuConsultarEstoque = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuCadastrarAcessorio = new javax.swing.JMenuItem();
        BotaoCadastrarBola = new javax.swing.JMenuItem();
        BotaoCadastrarCamiseta = new javax.swing.JMenuItem();
        BotaoCadastrarChuteira = new javax.swing.JMenuItem();
        BotaoCadastrarCliente = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toca a Bola");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo.png"))); // NOI18N
        jLabelFundo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabelFundo)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabelFundo)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jMenuRealizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo100h.png"))); // NOI18N
        jMenuRealizarVenda.setText("Realizar Venda");
        jMenuRealizarVenda.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jMenuRealizarVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuRealizarVendaMouseClicked(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuRealizarVenda);

        jMenuHistoricoVenda.setText("Histórico de Vendas");
        jMenuHistoricoVenda.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jMenuHistoricoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHistoricoVendaMouseClicked(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuHistoricoVenda);

        jMenuConsultarEstoque.setText("Consultar Estoque");
        jMenuConsultarEstoque.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jMenuConsultarEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConsultarEstoqueMouseClicked(evt);
            }
        });
        jMenuConsultarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultarEstoqueActionPerformed(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuConsultarEstoque);

        jMenuCadastrar.setText("Cadastrar Produto");
        jMenuCadastrar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N

        jMenuCadastrarAcessorio.setFont(new java.awt.Font("Juventus Fans Bold", 0, 14)); // NOI18N
        jMenuCadastrarAcessorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-direita (1).png"))); // NOI18N
        jMenuCadastrarAcessorio.setText("Cadastrar Acessório");
        jMenuCadastrarAcessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarAcessorioAcao(evt);
            }
        });
        jMenuCadastrar.add(jMenuCadastrarAcessorio);

        BotaoCadastrarBola.setFont(new java.awt.Font("Juventus Fans Bold", 0, 14)); // NOI18N
        BotaoCadastrarBola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-direita (1).png"))); // NOI18N
        BotaoCadastrarBola.setText("Cadastrar Bola");
        BotaoCadastrarBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarBolaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(BotaoCadastrarBola);

        BotaoCadastrarCamiseta.setFont(new java.awt.Font("Juventus Fans Bold", 0, 14)); // NOI18N
        BotaoCadastrarCamiseta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-direita (1).png"))); // NOI18N
        BotaoCadastrarCamiseta.setText("Cadastrar Camiseta");
        BotaoCadastrarCamiseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarCamisetaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(BotaoCadastrarCamiseta);

        BotaoCadastrarChuteira.setFont(new java.awt.Font("Juventus Fans Bold", 0, 14)); // NOI18N
        BotaoCadastrarChuteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-direita (1).png"))); // NOI18N
        BotaoCadastrarChuteira.setText("Cadastrar Chuteira");
        BotaoCadastrarChuteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarChuteiraActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(BotaoCadastrarChuteira);

        BotaoCadastrarCliente.setFont(new java.awt.Font("Juventus Fans Bold", 0, 14)); // NOI18N
        BotaoCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/seta-direita (1).png"))); // NOI18N
        BotaoCadastrarCliente.setText("Cadastrar Cliente");
        BotaoCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarClienteActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(BotaoCadastrarCliente);

        jMenuBarTelaPrincipal.add(jMenuCadastrar);

        jMenuSair.setText("Sair");
        jMenuSair.setFont(new java.awt.Font("Juventus Fans Bold", 0, 24)); // NOI18N
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBarTelaPrincipal.add(jMenuSair);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarAcessorioAcao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarAcessorioAcao
        TelaCadastroAcessorio telaCadastroAcessorio = new TelaCadastroAcessorio();
        telaCadastroAcessorio.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_BotaoCadastrarAcessorioAcao

    private void BotaoCadastrarCamisetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarCamisetaActionPerformed
        TelaCadastroCamisetas telaCadastroCamisetas = new TelaCadastroCamisetas();
        telaCadastroCamisetas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoCadastrarCamisetaActionPerformed

    private void BotaoCadastrarChuteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarChuteiraActionPerformed
       TelaCadastroChuteiras telaCadastroChuteiras = new TelaCadastroChuteiras();
       telaCadastroChuteiras.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BotaoCadastrarChuteiraActionPerformed

    private void BotaoCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarClienteActionPerformed
       TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
       telaCadastroCliente.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BotaoCadastrarClienteActionPerformed

    private void BotaoCadastrarBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarBolaActionPerformed
        TelaCadastroBola telaCadastroBola = new TelaCadastroBola();
        telaCadastroBola.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BotaoCadastrarBolaActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void jMenuConsultarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuConsultarEstoqueActionPerformed

    private void jMenuConsultarEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultarEstoqueMouseClicked
        TelaConsultaEstoque telaConsultaEstoque = new TelaConsultaEstoque();
        telaConsultaEstoque.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuConsultarEstoqueMouseClicked

    private void jMenuRealizarVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuRealizarVendaMouseClicked
        TelaRealizarVenda telaRealizarVenda = new TelaRealizarVenda();
        telaRealizarVenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuRealizarVendaMouseClicked

    private void jMenuHistoricoVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHistoricoVendaMouseClicked
        TelaConsultaVendas telaConsultaVendas = new TelaConsultaVendas();
        telaConsultaVendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuHistoricoVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BotaoCadastrarBola;
    private javax.swing.JMenuItem BotaoCadastrarCamiseta;
    private javax.swing.JMenuItem BotaoCadastrarChuteira;
    private javax.swing.JMenuItem BotaoCadastrarCliente;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenuItem jMenuCadastrarAcessorio;
    private javax.swing.JMenu jMenuConsultarEstoque;
    private javax.swing.JMenu jMenuHistoricoVenda;
    private javax.swing.JMenu jMenuRealizarVenda;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
