/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gabri
 */
public class TelaConsultaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEstoque
     */
    private TelaPrincipal telaPrincipal;
    private TelaConsultaEstoqueAcessórios telaConsultaEstoqueAcessórios;
    private TelaConsultaEstoqueBolas telaConsultaEstoqueBolas;
    private TelaConsultaEstoqueCamisetas telaConsultaEstoqueCamisetas;
    private TelaConsultaEstoqueChuteiras telaConsultaEstoqueChuteiras;
    private TelaConsultaClientesCadastrados telaConsultaClientesCadastrados;
    
    public TelaConsultaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ConsultaEstoqueTitulo = new javax.swing.JLabel();
        BotaoVoltar = new javax.swing.JButton();
        BotaoConsultarCliente1 = new javax.swing.JButton();
        BotaoConsultarAcessorios1 = new javax.swing.JButton();
        BotaoConsultarBolas1 = new javax.swing.JButton();
        BotaoConsultarCamisetas1 = new javax.swing.JButton();
        BotaoConsultarChuteiras1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toca a Bola -> Consulta de Itens");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 400));

        ConsultaEstoqueTitulo.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        ConsultaEstoqueTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/toca a bola logo.png"))); // NOI18N
        ConsultaEstoqueTitulo.setText("Consultar Itens Cadastrados");
        ConsultaEstoqueTitulo.setMaximumSize(new java.awt.Dimension(484, 169));
        ConsultaEstoqueTitulo.setMinimumSize(new java.awt.Dimension(484, 169));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(ConsultaEstoqueTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ConsultaEstoqueTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        BotaoVoltar.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.setActionCommand("Consultar Camisetas");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        BotaoConsultarCliente1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoConsultarCliente1.setText("Consultar Cliente");
        BotaoConsultarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarCliente1ActionPerformed(evt);
            }
        });

        BotaoConsultarAcessorios1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoConsultarAcessorios1.setText("Consultar Acessórios");
        BotaoConsultarAcessorios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarAcessorios1ActionPerformed(evt);
            }
        });

        BotaoConsultarBolas1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoConsultarBolas1.setText("Consultar Bolas");
        BotaoConsultarBolas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarBolas1ActionPerformed(evt);
            }
        });

        BotaoConsultarCamisetas1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoConsultarCamisetas1.setText("Consultar Camisetas");
        BotaoConsultarCamisetas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarCamisetas1ActionPerformed(evt);
            }
        });

        BotaoConsultarChuteiras1.setFont(new java.awt.Font("Juventus Fans Bold", 0, 36)); // NOI18N
        BotaoConsultarChuteiras1.setText("Consultar Chuteiras");
        BotaoConsultarChuteiras1.setActionCommand("Consultar Camisetas");
        BotaoConsultarChuteiras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoConsultarChuteiras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotaoConsultarCliente1)
                .addGap(171, 171, 171)
                .addComponent(BotaoVoltar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoConsultarAcessorios1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoConsultarCamisetas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoConsultarChuteiras1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoConsultarBolas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConsultarBolas1)
                    .addComponent(BotaoConsultarAcessorios1))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoConsultarChuteiras1)
                    .addComponent(BotaoConsultarCamisetas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoVoltar)
                    .addComponent(BotaoConsultarCliente1))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    private void BotaoConsultarBolas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarBolas1ActionPerformed
        TelaConsultaEstoqueBolas telaConsultaEstoqueBolas = new TelaConsultaEstoqueBolas();
        telaConsultaEstoqueBolas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoConsultarBolas1ActionPerformed

    private void BotaoConsultarCamisetas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarCamisetas1ActionPerformed
        TelaConsultaEstoqueCamisetas telaConsultaEstoqueCamisetas = new TelaConsultaEstoqueCamisetas();
        telaConsultaEstoqueCamisetas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoConsultarCamisetas1ActionPerformed

    private void BotaoConsultarChuteiras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarChuteiras1ActionPerformed
        TelaConsultaEstoqueChuteiras telaConsultaEstoqueChuteiras = new TelaConsultaEstoqueChuteiras();
        telaConsultaEstoqueChuteiras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoConsultarChuteiras1ActionPerformed

    private void BotaoConsultarAcessorios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarAcessorios1ActionPerformed
        TelaConsultaEstoqueAcessórios telaConsultaEstoqueAcessórios = new TelaConsultaEstoqueAcessórios();
        telaConsultaEstoqueAcessórios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoConsultarAcessorios1ActionPerformed

    private void BotaoConsultarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoConsultarCliente1ActionPerformed
        TelaConsultaClientesCadastrados telaConsultaClientesCadastrados = new TelaConsultaClientesCadastrados();
        telaConsultaClientesCadastrados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoConsultarCliente1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoConsultarAcessorios1;
    private javax.swing.JButton BotaoConsultarBolas1;
    private javax.swing.JButton BotaoConsultarCamisetas1;
    private javax.swing.JButton BotaoConsultarChuteiras1;
    private javax.swing.JButton BotaoConsultarCliente1;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JLabel ConsultaEstoqueTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
